package com.xqls.dal.service;

import com.xqls.dal.model.OperationRecord;
import com.xqls.dal.model.OperationRecordExample;
import com.xqls.dal.model.OperationRecordKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OperationRecordMapper {
	
	List<Map<String, Object>> selectByMap(Map<String, Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int countByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int deleteByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(OperationRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int insert(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int insertSelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    List<OperationRecord> selectByExample(OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    OperationRecord selectByPrimaryKey(OperationRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OperationRecord record, @Param("example") OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OperationRecord record, @Param("example") OperationRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OperationRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OperationRecord record);
}