package com.skeye.yagout.dal.service;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.skeye.yagout.dal.model.YagoutRoles;
import com.skeye.yagout.dal.model.YagoutRolesExample;

public interface YagoutRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int countByExample(YagoutRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int deleteByExample(YagoutRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int insert(YagoutRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int insertSelective(YagoutRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    List<YagoutRoles> selectByExample(YagoutRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    YagoutRoles selectByPrimaryKey(Integer roleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YagoutRoles record, @Param("example") YagoutRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YagoutRoles record, @Param("example") YagoutRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YagoutRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_roles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YagoutRoles record);
    
    Set<String> getRolesByName(@Param("userName")String userName);



}