package com.yagout.defense.dal.service;

import com.yagout.defense.dal.model.StationVisitor;
import com.yagout.defense.dal.model.StationVisitorExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface StationVisitorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int countByExample(StationVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int deleteByExample(StationVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int insert(StationVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int insertSelective(StationVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    List<StationVisitor> selectByExample(StationVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    StationVisitor selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationVisitor record, @Param("example") StationVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationVisitor record, @Param("example") StationVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationVisitor record);
    
    List<Map<String,Object>> selectAll(Map<String,Object> map);
}