package com.yagout.defense.dal.service;

import com.yagout.defense.dal.model.DefenseType;
import com.yagout.defense.dal.model.DefenseTypeExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DefenseTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int countByExample(DefenseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int deleteByExample(DefenseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer defenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int insert(DefenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int insertSelective(DefenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    List<DefenseType> selectByExample(DefenseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    DefenseType selectByPrimaryKey(Integer defenseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DefenseType record, @Param("example") DefenseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DefenseType record, @Param("example") DefenseTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DefenseType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defense_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DefenseType record);
    
    List<DefenseType> getDefenseTypeByMap(Map<String,Object> map);
}