package com.yagout.defense.dal.service;

import com.yagout.defense.dal.model.LoginCheck;
import com.yagout.defense.dal.model.LoginCheckExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface LoginCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int countByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int deleteByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int insert(LoginCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int insertSelective(LoginCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    List<LoginCheck> selectByExample(LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    LoginCheck selectByPrimaryKey(Long rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LoginCheck record, @Param("example") LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LoginCheck record, @Param("example") LoginCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LoginCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_check
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LoginCheck record);
    
    List<LoginCheck> getLoginCheckByMap(Map<String,Object> map);
    
    List<LoginCheck> getLoginCheckForLogin(Map<String, Object> map);
    
    int recoveLoginByList(List<Long> rowIdList);
}