package com.skeye.water_fountain.dal.service;

import com.skeye.water_fountain.dal.model.AccountDevice;
import com.skeye.water_fountain.dal.model.AccountDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int countByExample(AccountDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int deleteByExample(AccountDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int insert(AccountDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int insertSelective(AccountDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    List<AccountDevice> selectByExample(AccountDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    AccountDevice selectByPrimaryKey(String rowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccountDevice record, @Param("example") AccountDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccountDevice record, @Param("example") AccountDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountDevice record);
}