package com.skeye.water_fountain.dal.service;

import com.skeye.water_fountain.dal.model.DeviceState;
import com.skeye.water_fountain.dal.model.DeviceStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DeviceStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int countByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int deleteByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String recordNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int insert(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int insertSelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    List<DeviceState> selectByExample(DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    DeviceState selectByPrimaryKey(String recordNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeviceState record, @Param("example") DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeviceState record, @Param("example") DeviceStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeviceState record);
}