package com.yagout.defense.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.ApNeighbor;
import com.yagout.defense.dal.model.ApNeighborExample;

public interface ApNeighborMapper {
	
	
	int batchUpdate(Map<String,List<ApNeighbor>> apNeighborList);
	
	int batchInsert(Map<String,List<ApNeighbor>> apNeighborList);
	
	int deleteApNeighbors(List<String> macs);
	
    List<Map<String,Object>> selectAll(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int countByExample(ApNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int deleteByExample(ApNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int insert(ApNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int insertSelective(ApNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    List<ApNeighbor> selectByExample(ApNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    ApNeighbor selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApNeighbor record, @Param("example") ApNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApNeighbor record, @Param("example") ApNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_neighbor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApNeighbor record);
}