package com.xqls.bean;

import java.util.Date;

public class OperationRecordBean extends OperationRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.record_time
     *
     * @mbggenerated
     */
    private Date recordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.modular_no
     *
     * @mbggenerated
     */
    private Integer modularNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_type
     *
     * @mbggenerated
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.record_content
     *
     * @mbggenerated
     */
    private String recordContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.tenant_no
     *
     * @mbggenerated
     */
    private String tenantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_record.operation_source
     *
     * @mbggenerated
     */
    private String operationSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.record_time
     *
     * @return the value of operation_record.record_time
     *
     * @mbggenerated
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.record_time
     *
     * @param recordTime the value for operation_record.record_time
     *
     * @mbggenerated
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.modular_no
     *
     * @return the value of operation_record.modular_no
     *
     * @mbggenerated
     */
    public Integer getModularNo() {
        return modularNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.modular_no
     *
     * @param modularNo the value for operation_record.modular_no
     *
     * @mbggenerated
     */
    public void setModularNo(Integer modularNo) {
        this.modularNo = modularNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_type
     *
     * @return the value of operation_record.operation_type
     *
     * @mbggenerated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_type
     *
     * @param operationType the value for operation_record.operation_type
     *
     * @mbggenerated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.record_content
     *
     * @return the value of operation_record.record_content
     *
     * @mbggenerated
     */
    public String getRecordContent() {
        return recordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.record_content
     *
     * @param recordContent the value for operation_record.record_content
     *
     * @mbggenerated
     */
    public void setRecordContent(String recordContent) {
        this.recordContent = recordContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.tenant_no
     *
     * @return the value of operation_record.tenant_no
     *
     * @mbggenerated
     */
    public String getTenantNo() {
        return tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.tenant_no
     *
     * @param tenantNo the value for operation_record.tenant_no
     *
     * @mbggenerated
     */
    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_record.operation_source
     *
     * @return the value of operation_record.operation_source
     *
     * @mbggenerated
     */
    public String getOperationSource() {
        return operationSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_record.operation_source
     *
     * @param operationSource the value for operation_record.operation_source
     *
     * @mbggenerated
     */
    public void setOperationSource(String operationSource) {
        this.operationSource = operationSource;
    }
}