package com.skeye.yagout.biz.bean;

import org.hibernate.validator.constraints.NotEmpty;

import java.io.Serializable;

public class YagoutUsersBean implements Serializable{

    private static final long serialVersionUID = 8270642884503922726L;
    private Integer id;

    @NotEmpty(message = "登录名不能为空")
    private String userName;

    @NotEmpty(message = "登录密码不能为空")
    private String password;

    private String rePeatPassword;

    private String newPassword;


    private String roleName;

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getRePeatPassword() {
        return rePeatPassword;
    }

    public void setRePeatPassword(String rePeatPassword) {
        this.rePeatPassword = rePeatPassword;
    }

    public YagoutUsersBean(){}



    public YagoutUsersBean(String userName ,String password,Integer id){
        this.setId(id);
        this.setUserName(userName);
        this.setPassword(password);
    }



    public String getCredentialsSalt() {
        return userName ;
    }
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_users.user_name
     *
     * @param userName the value for yagout_users.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_users.password
     *
     * @return the value of yagout_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_users.password
     *
     * @param password the value for yagout_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}