package com.skeye.yagout.dal.model;

public class YagoutUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yagout_users.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yagout_users.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yagout_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_users.ID
     *
     * @return the value of yagout_users.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_users.ID
     *
     * @param id the value for yagout_users.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_users.user_name
     *
     * @return the value of yagout_users.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_users.user_name
     *
     * @param userName the value for yagout_users.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_users.password
     *
     * @return the value of yagout_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_users.password
     *
     * @param password the value for yagout_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}