package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.YagoutLog;
import com.skeye.yagout.dal.model.YagoutLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface YagoutLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int countByExample(YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int deleteByExample(YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int insert(YagoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int insertSelective(YagoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    List<YagoutLog> selectByExampleWithBLOBs(YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    List<YagoutLog> selectByExample(YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    YagoutLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YagoutLog record, @Param("example") YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") YagoutLog record, @Param("example") YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YagoutLog record, @Param("example") YagoutLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(YagoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(YagoutLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(YagoutLog record);



    List<Map> getLogByMap(Map<String, Object> map);
}