package com.yagout.defense.dal.service;

import com.yagout.defense.dal.model.StationNeighbor;
import com.yagout.defense.dal.model.StationNeighborExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface StationNeighborMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int countByExample(StationNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int deleteByExample(StationNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int insert(StationNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int insertSelective(StationNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    List<StationNeighbor> selectByExample(StationNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    StationNeighbor selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StationNeighbor record, @Param("example") StationNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StationNeighbor record, @Param("example") StationNeighborExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StationNeighbor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_neighbor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StationNeighbor record);
    
    List<Map<String,Object>> selectAll(Map<String,Object> map);
}