package com.skeye.yagout.dal.model;

public class Rawaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.AccountName
     *
     * @mbggenerated
     */
    private String accountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.AccountType
     *
     * @mbggenerated
     */
    private Integer accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.AdslAccount
     *
     * @mbggenerated
     */
    private String adslaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.MacAddr
     *
     * @mbggenerated
     */
    private String macaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.IpAddr
     *
     * @mbggenerated
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.CapTime
     *
     * @mbggenerated
     */
    private Integer captime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.CapIP
     *
     * @mbggenerated
     */
    private Integer capip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.Handled
     *
     * @mbggenerated
     */
    private Integer handled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount.CapPort
     *
     * @mbggenerated
     */
    private Integer capport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.ID
     *
     * @return the value of rawaccount.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.ID
     *
     * @param id the value for rawaccount.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.AccountName
     *
     * @return the value of rawaccount.AccountName
     *
     * @mbggenerated
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.AccountName
     *
     * @param accountname the value for rawaccount.AccountName
     *
     * @mbggenerated
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.Password
     *
     * @return the value of rawaccount.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.Password
     *
     * @param password the value for rawaccount.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.AccountType
     *
     * @return the value of rawaccount.AccountType
     *
     * @mbggenerated
     */
    public Integer getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.AccountType
     *
     * @param accounttype the value for rawaccount.AccountType
     *
     * @mbggenerated
     */
    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.AdslAccount
     *
     * @return the value of rawaccount.AdslAccount
     *
     * @mbggenerated
     */
    public String getAdslaccount() {
        return adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.AdslAccount
     *
     * @param adslaccount the value for rawaccount.AdslAccount
     *
     * @mbggenerated
     */
    public void setAdslaccount(String adslaccount) {
        this.adslaccount = adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.MacAddr
     *
     * @return the value of rawaccount.MacAddr
     *
     * @mbggenerated
     */
    public String getMacaddr() {
        return macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.MacAddr
     *
     * @param macaddr the value for rawaccount.MacAddr
     *
     * @mbggenerated
     */
    public void setMacaddr(String macaddr) {
        this.macaddr = macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.IpAddr
     *
     * @return the value of rawaccount.IpAddr
     *
     * @mbggenerated
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.IpAddr
     *
     * @param ipaddr the value for rawaccount.IpAddr
     *
     * @mbggenerated
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.CapTime
     *
     * @return the value of rawaccount.CapTime
     *
     * @mbggenerated
     */
    public Integer getCaptime() {
        return captime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.CapTime
     *
     * @param captime the value for rawaccount.CapTime
     *
     * @mbggenerated
     */
    public void setCaptime(Integer captime) {
        this.captime = captime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.CapIP
     *
     * @return the value of rawaccount.CapIP
     *
     * @mbggenerated
     */
    public Integer getCapip() {
        return capip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.CapIP
     *
     * @param capip the value for rawaccount.CapIP
     *
     * @mbggenerated
     */
    public void setCapip(Integer capip) {
        this.capip = capip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.Handled
     *
     * @return the value of rawaccount.Handled
     *
     * @mbggenerated
     */
    public Integer getHandled() {
        return handled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.Handled
     *
     * @param handled the value for rawaccount.Handled
     *
     * @mbggenerated
     */
    public void setHandled(Integer handled) {
        this.handled = handled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount.CapPort
     *
     * @return the value of rawaccount.CapPort
     *
     * @mbggenerated
     */
    public Integer getCapport() {
        return capport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount.CapPort
     *
     * @param capport the value for rawaccount.CapPort
     *
     * @mbggenerated
     */
    public void setCapport(Integer capport) {
        this.capport = capport;
    }
}