package com.skeye.yagout.dal.model;

public class RawaccountHandled {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.AccountName
     *
     * @mbggenerated
     */
    private String accountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.AccountType
     *
     * @mbggenerated
     */
    private Integer accounttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.ADSLAccount
     *
     * @mbggenerated
     */
    private String adslaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.MacAddr
     *
     * @mbggenerated
     */
    private String macaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.IPAddr
     *
     * @mbggenerated
     */
    private String ipaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.CapTime
     *
     * @mbggenerated
     */
    private Integer captime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rawaccount_handled.CapPort
     *
     * @mbggenerated
     */
    private Integer capport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.ID
     *
     * @return the value of rawaccount_handled.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.ID
     *
     * @param id the value for rawaccount_handled.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.AccountName
     *
     * @return the value of rawaccount_handled.AccountName
     *
     * @mbggenerated
     */
    public String getAccountname() {
        return accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.AccountName
     *
     * @param accountname the value for rawaccount_handled.AccountName
     *
     * @mbggenerated
     */
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.Password
     *
     * @return the value of rawaccount_handled.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.Password
     *
     * @param password the value for rawaccount_handled.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.AccountType
     *
     * @return the value of rawaccount_handled.AccountType
     *
     * @mbggenerated
     */
    public Integer getAccounttype() {
        return accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.AccountType
     *
     * @param accounttype the value for rawaccount_handled.AccountType
     *
     * @mbggenerated
     */
    public void setAccounttype(Integer accounttype) {
        this.accounttype = accounttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.ADSLAccount
     *
     * @return the value of rawaccount_handled.ADSLAccount
     *
     * @mbggenerated
     */
    public String getAdslaccount() {
        return adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.ADSLAccount
     *
     * @param adslaccount the value for rawaccount_handled.ADSLAccount
     *
     * @mbggenerated
     */
    public void setAdslaccount(String adslaccount) {
        this.adslaccount = adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.MacAddr
     *
     * @return the value of rawaccount_handled.MacAddr
     *
     * @mbggenerated
     */
    public String getMacaddr() {
        return macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.MacAddr
     *
     * @param macaddr the value for rawaccount_handled.MacAddr
     *
     * @mbggenerated
     */
    public void setMacaddr(String macaddr) {
        this.macaddr = macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.IPAddr
     *
     * @return the value of rawaccount_handled.IPAddr
     *
     * @mbggenerated
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.IPAddr
     *
     * @param ipaddr the value for rawaccount_handled.IPAddr
     *
     * @mbggenerated
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.CapTime
     *
     * @return the value of rawaccount_handled.CapTime
     *
     * @mbggenerated
     */
    public Integer getCaptime() {
        return captime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.CapTime
     *
     * @param captime the value for rawaccount_handled.CapTime
     *
     * @mbggenerated
     */
    public void setCaptime(Integer captime) {
        this.captime = captime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rawaccount_handled.CapPort
     *
     * @return the value of rawaccount_handled.CapPort
     *
     * @mbggenerated
     */
    public Integer getCapport() {
        return capport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rawaccount_handled.CapPort
     *
     * @param capport the value for rawaccount_handled.CapPort
     *
     * @mbggenerated
     */
    public void setCapport(Integer capport) {
        this.capport = capport;
    }

	@Override
	public String toString() {
		return "RawaccountHandled [id=" + id + ", accountname=" + accountname + ", password=" + password
				+ ", accounttype=" + accounttype + ", adslaccount=" + adslaccount + ", macaddr=" + macaddr + ", ipaddr="
				+ ipaddr + ", captime=" + captime + ", capport=" + capport + "]";
	}
	
	public String[] getRawaccountHandledForArray()
	{
		String[] values={String.valueOf(this.id),this.accountname,this.password,String.valueOf(this.accounttype),this.adslaccount,
				this.macaddr,this.ipaddr,String.valueOf(this.captime),String.valueOf(this.capport)};
		return values;
	}
	
}