package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.RawaccountHandled;
import com.skeye.yagout.dal.model.RawaccountHandledExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RawaccountHandledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int countByExample(RawaccountHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int deleteByExample(RawaccountHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int insert(RawaccountHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int insertSelective(RawaccountHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    List<RawaccountHandled> selectByExample(RawaccountHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    RawaccountHandled selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RawaccountHandled record, @Param("example") RawaccountHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RawaccountHandled record, @Param("example") RawaccountHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RawaccountHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rawaccount_handled
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RawaccountHandled record);
    

    List<Map> selectByMap(Map<String,Object> paramMap);

    List<Map> selectGroupByMap(Map<String,Object> paramMap);
}