package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.Account;
import com.skeye.yagout.dal.model.DailinfoHandled;
import com.skeye.yagout.dal.model.DailinfoHandledExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface DailinfoHandledMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int countByExample(DailinfoHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int deleteByExample(DailinfoHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int insert(DailinfoHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int insertSelective(DailinfoHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    List<DailinfoHandled> selectByExample(DailinfoHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    DailinfoHandled selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DailinfoHandled record, @Param("example") DailinfoHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DailinfoHandled record, @Param("example") DailinfoHandledExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DailinfoHandled record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dailinfo_handled
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DailinfoHandled record);
    
    List<Map> selectByMap(Map<String,Object> paramMap);
}