package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.Specialhostaccess;
import com.skeye.yagout.dal.model.SpecialhostaccessExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialhostaccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int countByExample(SpecialhostaccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialhostaccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int insert(Specialhostaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int insertSelective(Specialhostaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    List<Specialhostaccess> selectByExample(SpecialhostaccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    Specialhostaccess selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Specialhostaccess record, @Param("example") SpecialhostaccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Specialhostaccess record, @Param("example") SpecialhostaccessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Specialhostaccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialhostaccess
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Specialhostaccess record);
}