package com.yagout.defense.dal.model;

public class ApVisitor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.ssid
     *
     * @mbggenerated
     */
    private String ssid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.maker
     *
     * @mbggenerated
     */
    private String maker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.privacy
     *
     * @mbggenerated
     */
    private Integer privacy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.reserved1
     *
     * @mbggenerated
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.reserved2
     *
     * @mbggenerated
     */
    private Integer reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.beacon_size
     *
     * @mbggenerated
     */
    private Integer beaconSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.beacon
     *
     * @mbggenerated
     */
    private String beacon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.probe_response_size
     *
     * @mbggenerated
     */
    private Integer probeResponseSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ap_visitor.probe_response
     *
     * @mbggenerated
     */
    private String probeResponse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.mac
     *
     * @return the value of ap_visitor.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.mac
     *
     * @param mac the value for ap_visitor.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.ssid
     *
     * @return the value of ap_visitor.ssid
     *
     * @mbggenerated
     */
    public String getSsid() {
        return ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.ssid
     *
     * @param ssid the value for ap_visitor.ssid
     *
     * @mbggenerated
     */
    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.pwd
     *
     * @return the value of ap_visitor.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.pwd
     *
     * @param pwd the value for ap_visitor.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.maker
     *
     * @return the value of ap_visitor.maker
     *
     * @mbggenerated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.maker
     *
     * @param maker the value for ap_visitor.maker
     *
     * @mbggenerated
     */
    public void setMaker(String maker) {
        this.maker = maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.remarks
     *
     * @return the value of ap_visitor.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.remarks
     *
     * @param remarks the value for ap_visitor.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.privacy
     *
     * @return the value of ap_visitor.privacy
     *
     * @mbggenerated
     */
    public Integer getPrivacy() {
        return privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.privacy
     *
     * @param privacy the value for ap_visitor.privacy
     *
     * @mbggenerated
     */
    public void setPrivacy(Integer privacy) {
        this.privacy = privacy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.reserved1
     *
     * @return the value of ap_visitor.reserved1
     *
     * @mbggenerated
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.reserved1
     *
     * @param reserved1 the value for ap_visitor.reserved1
     *
     * @mbggenerated
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.reserved2
     *
     * @return the value of ap_visitor.reserved2
     *
     * @mbggenerated
     */
    public Integer getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.reserved2
     *
     * @param reserved2 the value for ap_visitor.reserved2
     *
     * @mbggenerated
     */
    public void setReserved2(Integer reserved2) {
        this.reserved2 = reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.beacon_size
     *
     * @return the value of ap_visitor.beacon_size
     *
     * @mbggenerated
     */
    public Integer getBeaconSize() {
        return beaconSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.beacon_size
     *
     * @param beaconSize the value for ap_visitor.beacon_size
     *
     * @mbggenerated
     */
    public void setBeaconSize(Integer beaconSize) {
        this.beaconSize = beaconSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.beacon
     *
     * @return the value of ap_visitor.beacon
     *
     * @mbggenerated
     */
    public String getBeacon() {
        return beacon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.beacon
     *
     * @param beacon the value for ap_visitor.beacon
     *
     * @mbggenerated
     */
    public void setBeacon(String beacon) {
        this.beacon = beacon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.probe_response_size
     *
     * @return the value of ap_visitor.probe_response_size
     *
     * @mbggenerated
     */
    public Integer getProbeResponseSize() {
        return probeResponseSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.probe_response_size
     *
     * @param probeResponseSize the value for ap_visitor.probe_response_size
     *
     * @mbggenerated
     */
    public void setProbeResponseSize(Integer probeResponseSize) {
        this.probeResponseSize = probeResponseSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ap_visitor.probe_response
     *
     * @return the value of ap_visitor.probe_response
     *
     * @mbggenerated
     */
    public String getProbeResponse() {
        return probeResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ap_visitor.probe_response
     *
     * @param probeResponse the value for ap_visitor.probe_response
     *
     * @mbggenerated
     */
    public void setProbeResponse(String probeResponse) {
        this.probeResponse = probeResponse;
    }
}