package com.yagout.defense.dal.model;

public class StationTrust {
    
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.mac
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String mac;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.maker
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String maker;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.name
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.phone_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String phoneNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.id_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String idNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.department
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String department;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.remarks
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.reserved1
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private Integer reserved1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column station_trust.reserved2
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	private Integer reserved2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.mac
	 * @return  the value of station_trust.mac
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getMac() {
		return mac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.mac
	 * @param mac  the value for station_trust.mac
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setMac(String mac) {
		this.mac = mac == null ? null : mac.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.maker
	 * @return  the value of station_trust.maker
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getMaker() {
		return maker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.maker
	 * @param maker  the value for station_trust.maker
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setMaker(String maker) {
		this.maker = maker == null ? null : maker.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.name
	 * @return  the value of station_trust.name
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.name
	 * @param name  the value for station_trust.name
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.phone_number
	 * @return  the value of station_trust.phone_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.phone_number
	 * @param phoneNumber  the value for station_trust.phone_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.id_number
	 * @return  the value of station_trust.id_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.id_number
	 * @param idNumber  the value for station_trust.id_number
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber == null ? null : idNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.department
	 * @return  the value of station_trust.department
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.department
	 * @param department  the value for station_trust.department
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setDepartment(String department) {
		this.department = department == null ? null : department.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.remarks
	 * @return  the value of station_trust.remarks
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.remarks
	 * @param remarks  the value for station_trust.remarks
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks == null ? null : remarks.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.reserved1
	 * @return  the value of station_trust.reserved1
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public Integer getReserved1() {
		return reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.reserved1
	 * @param reserved1  the value for station_trust.reserved1
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setReserved1(Integer reserved1) {
		this.reserved1 = reserved1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column station_trust.reserved2
	 * @return  the value of station_trust.reserved2
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public Integer getReserved2() {
		return reserved2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column station_trust.reserved2
	 * @param reserved2  the value for station_trust.reserved2
	 * @mbggenerated  Thu Feb 09 10:30:45 CST 2017
	 */
	public void setReserved2(Integer reserved2) {
		this.reserved2 = reserved2;
	}

	public StationTrust() {
		super();
	}

	public StationTrust(String mac, String maker, String name,
			String phoneNumber, String idNumber, String department,
			String remarks) {
		super();
		this.mac = mac;
		this.maker = maker;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.idNumber = idNumber;
		this.department = department;
		this.remarks = remarks;
	}
	
	

	
    
}