package com.yagout.defense.dal.model;

public class UserLogEventType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log_event_type.event_type
     *
     * @mbggenerated
     */
    private Integer eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log_event_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log_event_type.type_desc
     *
     * @mbggenerated
     */
    private String typeDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log_event_type.event_type
     *
     * @return the value of user_log_event_type.event_type
     *
     * @mbggenerated
     */
    public Integer getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log_event_type.event_type
     *
     * @param eventType the value for user_log_event_type.event_type
     *
     * @mbggenerated
     */
    public void setEventType(Integer eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log_event_type.type_name
     *
     * @return the value of user_log_event_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log_event_type.type_name
     *
     * @param typeName the value for user_log_event_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log_event_type.type_desc
     *
     * @return the value of user_log_event_type.type_desc
     *
     * @mbggenerated
     */
    public String getTypeDesc() {
        return typeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log_event_type.type_desc
     *
     * @param typeDesc the value for user_log_event_type.type_desc
     *
     * @mbggenerated
     */
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }
}