package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.Accounttype;
import com.skeye.yagout.dal.model.AccounttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccounttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int countByExample(AccounttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int deleteByExample(AccounttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int insert(Accounttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int insertSelective(Accounttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    List<Accounttype> selectByExample(AccounttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    Accounttype selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Accounttype record, @Param("example") AccounttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Accounttype record, @Param("example") AccounttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Accounttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounttype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Accounttype record);
}