package com.skeye.yagout.dal.service;

import com.skeye.yagout.dal.model.YagoutUserRoleExample;
import com.skeye.yagout.dal.model.YagoutUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YagoutUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int countByExample(YagoutUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(YagoutUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(YagoutUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int insert(YagoutUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int insertSelective(YagoutUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    List<YagoutUserRoleKey> selectByExample(YagoutUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") YagoutUserRoleKey record, @Param("example") YagoutUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yagout_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") YagoutUserRoleKey record, @Param("example") YagoutUserRoleExample example);
}