package com.skeye.yagout.dal.model;

public class Sessioninfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.LineID
     *
     * @mbggenerated
     */
    private Integer lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.OnTime
     *
     * @mbggenerated
     */
    private Integer ontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.OffTime
     *
     * @mbggenerated
     */
    private Integer offtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.SessionIP
     *
     * @mbggenerated
     */
    private Integer sessionip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.SessionID
     *
     * @mbggenerated
     */
    private Integer sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sessioninfo.MAC
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.ID
     *
     * @return the value of sessioninfo.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.ID
     *
     * @param id the value for sessioninfo.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.LineID
     *
     * @return the value of sessioninfo.LineID
     *
     * @mbggenerated
     */
    public Integer getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.LineID
     *
     * @param lineid the value for sessioninfo.LineID
     *
     * @mbggenerated
     */
    public void setLineid(Integer lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.OnTime
     *
     * @return the value of sessioninfo.OnTime
     *
     * @mbggenerated
     */
    public Integer getOntime() {
        return ontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.OnTime
     *
     * @param ontime the value for sessioninfo.OnTime
     *
     * @mbggenerated
     */
    public void setOntime(Integer ontime) {
        this.ontime = ontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.OffTime
     *
     * @return the value of sessioninfo.OffTime
     *
     * @mbggenerated
     */
    public Integer getOfftime() {
        return offtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.OffTime
     *
     * @param offtime the value for sessioninfo.OffTime
     *
     * @mbggenerated
     */
    public void setOfftime(Integer offtime) {
        this.offtime = offtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.SessionIP
     *
     * @return the value of sessioninfo.SessionIP
     *
     * @mbggenerated
     */
    public Integer getSessionip() {
        return sessionip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.SessionIP
     *
     * @param sessionip the value for sessioninfo.SessionIP
     *
     * @mbggenerated
     */
    public void setSessionip(Integer sessionip) {
        this.sessionip = sessionip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.SessionID
     *
     * @return the value of sessioninfo.SessionID
     *
     * @mbggenerated
     */
    public Integer getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.SessionID
     *
     * @param sessionid the value for sessioninfo.SessionID
     *
     * @mbggenerated
     */
    public void setSessionid(Integer sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sessioninfo.MAC
     *
     * @return the value of sessioninfo.MAC
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sessioninfo.MAC
     *
     * @param mac the value for sessioninfo.MAC
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac;
    }
}