package com.yagout.defense.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.ApAdHoc;
import com.yagout.defense.dal.model.ApAdHocExample;

public interface ApAdHocMapper {
	int batchUpdate(Map<String,List<ApAdHoc>> apAdHocList);
	
	int batchInsert(Map<String,List<ApAdHoc>> apAdHocList);
	
	int deleteApAdHocs(List<String> macs);
	
    List<Map<String,Object>> selectAll(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int countByExample(ApAdHocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int deleteByExample(ApAdHocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int insert(ApAdHoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int insertSelective(ApAdHoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    List<ApAdHoc> selectByExample(ApAdHocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    ApAdHoc selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApAdHoc record, @Param("example") ApAdHocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApAdHoc record, @Param("example") ApAdHocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApAdHoc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_ad_hoc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApAdHoc record);
}