package com.yagout.defense.dal.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.DeviceMonitor;
import com.yagout.defense.dal.model.DeviceMonitorExample;

public interface DeviceMonitorMapper {
	List<DeviceMonitor> selAllDeviceMonitor();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    long countByExample(DeviceMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int deleteByExample(DeviceMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deviceSerial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int insert(DeviceMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int insertSelective(DeviceMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    List<DeviceMonitor> selectByExample(DeviceMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    DeviceMonitor selectByPrimaryKey(String deviceSerial);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeviceMonitor record, @Param("example") DeviceMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeviceMonitor record, @Param("example") DeviceMonitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeviceMonitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_monitor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeviceMonitor record);
}