package com.yagout.defense.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.ExceptionMac;
import com.yagout.defense.dal.model.ExceptionMacExample;

public interface ExceptionMacMapper {
	int batchUpdate(Map<String,List<ExceptionMac>> exceptionMacList);
	
	int batchInsert(Map<String,List<ExceptionMac>> exceptionMacList);
	
	int deleteExceptionMacs(List<String> macs);
	
    List<Map<String,Object>> selectAll(Map<String,Object> map);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int countByExample(ExceptionMacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int deleteByExample(ExceptionMacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int insert(ExceptionMac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int insertSelective(ExceptionMac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    List<ExceptionMac> selectByExample(ExceptionMacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    ExceptionMac selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExceptionMac record, @Param("example") ExceptionMacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExceptionMac record, @Param("example") ExceptionMacExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExceptionMac record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_mac
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExceptionMac record);
    
}