package com.yagout.defense.dal.model;

public class DefenseType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defense_type.defense_id
     *
     * @mbggenerated
     */
    private Integer defenseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defense_type.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defense_type.when
     *
     * @mbggenerated
     */
    private Integer when;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defense_type.reserved
     *
     * @mbggenerated
     */
    private Integer reserved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defense_type.des
     *
     * @mbggenerated
     */
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defense_type.defense_id
     *
     * @return the value of defense_type.defense_id
     *
     * @mbggenerated
     */
    public Integer getDefenseId() {
        return defenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defense_type.defense_id
     *
     * @param defenseId the value for defense_type.defense_id
     *
     * @mbggenerated
     */
    public void setDefenseId(Integer defenseId) {
        this.defenseId = defenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defense_type.name
     *
     * @return the value of defense_type.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defense_type.name
     *
     * @param name the value for defense_type.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defense_type.when
     *
     * @return the value of defense_type.when
     *
     * @mbggenerated
     */
    public Integer getWhen() {
        return when;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defense_type.when
     *
     * @param when the value for defense_type.when
     *
     * @mbggenerated
     */
    public void setWhen(Integer when) {
        this.when = when;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defense_type.reserved
     *
     * @return the value of defense_type.reserved
     *
     * @mbggenerated
     */
    public Integer getReserved() {
        return reserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defense_type.reserved
     *
     * @param reserved the value for defense_type.reserved
     *
     * @mbggenerated
     */
    public void setReserved(Integer reserved) {
        this.reserved = reserved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defense_type.des
     *
     * @return the value of defense_type.des
     *
     * @mbggenerated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defense_type.des
     *
     * @param des the value for defense_type.des
     *
     * @mbggenerated
     */
    public void setDes(String des) {
        this.des = des;
    }
}