package com.yagout.defense.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.ApTrust;
import com.yagout.defense.dal.model.ApTrustExample;

public interface ApTrustMapper {
	
	int batchUpdate(Map<String,List<ApTrust>> ApTrustList);
	
	int batchInsert(Map<String,List<ApTrust>> ApTrustList);
	
	int deleteApTrusts(List<String> macs);
	
	List<Map<String,Object>> selectAll(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int countByExample(ApTrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int deleteByExample(ApTrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int insert(ApTrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int insertSelective(ApTrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    List<ApTrust> selectByExample(ApTrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    ApTrust selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApTrust record, @Param("example") ApTrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApTrust record, @Param("example") ApTrustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApTrust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_trust
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApTrust record);
}