package com.skeye.yagout.dal.model;

import java.util.ArrayList;
import java.util.List;

public class AccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public AccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNull() {
            addCriterion("AccountName is null");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNotNull() {
            addCriterion("AccountName is not null");
            return (Criteria) this;
        }

        public Criteria andAccountnameEqualTo(String value) {
            addCriterion("AccountName =", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotEqualTo(String value) {
            addCriterion("AccountName <>", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThan(String value) {
            addCriterion("AccountName >", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThanOrEqualTo(String value) {
            addCriterion("AccountName >=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThan(String value) {
            addCriterion("AccountName <", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThanOrEqualTo(String value) {
            addCriterion("AccountName <=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLike(String value) {
            addCriterion("AccountName like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotLike(String value) {
            addCriterion("AccountName not like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameIn(List<String> values) {
            addCriterion("AccountName in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotIn(List<String> values) {
            addCriterion("AccountName not in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameBetween(String value1, String value2) {
            addCriterion("AccountName between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotBetween(String value1, String value2) {
            addCriterion("AccountName not between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("Password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("Password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("Password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("Password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("Password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("Password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("Password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("Password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("Password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("Password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("Password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("Password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("Password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("Password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIsNull() {
            addCriterion("AccountType is null");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIsNotNull() {
            addCriterion("AccountType is not null");
            return (Criteria) this;
        }

        public Criteria andAccounttypeEqualTo(Integer value) {
            addCriterion("AccountType =", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotEqualTo(Integer value) {
            addCriterion("AccountType <>", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeGreaterThan(Integer value) {
            addCriterion("AccountType >", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("AccountType >=", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeLessThan(Integer value) {
            addCriterion("AccountType <", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeLessThanOrEqualTo(Integer value) {
            addCriterion("AccountType <=", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIn(List<Integer> values) {
            addCriterion("AccountType in", values, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotIn(List<Integer> values) {
            addCriterion("AccountType not in", values, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeBetween(Integer value1, Integer value2) {
            addCriterion("AccountType between", value1, value2, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("AccountType not between", value1, value2, "accounttype");
            return (Criteria) this;
        }

        public Criteria andHistoryIsNull() {
            addCriterion("History is null");
            return (Criteria) this;
        }

        public Criteria andHistoryIsNotNull() {
            addCriterion("History is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryEqualTo(Integer value) {
            addCriterion("History =", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotEqualTo(Integer value) {
            addCriterion("History <>", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryGreaterThan(Integer value) {
            addCriterion("History >", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("History >=", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryLessThan(Integer value) {
            addCriterion("History <", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryLessThanOrEqualTo(Integer value) {
            addCriterion("History <=", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryIn(List<Integer> values) {
            addCriterion("History in", values, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotIn(List<Integer> values) {
            addCriterion("History not in", values, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryBetween(Integer value1, Integer value2) {
            addCriterion("History between", value1, value2, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotBetween(Integer value1, Integer value2) {
            addCriterion("History not between", value1, value2, "history");
            return (Criteria) this;
        }

        public Criteria andLastcapadslIsNull() {
            addCriterion("LastCapADSL is null");
            return (Criteria) this;
        }

        public Criteria andLastcapadslIsNotNull() {
            addCriterion("LastCapADSL is not null");
            return (Criteria) this;
        }

        public Criteria andLastcapadslEqualTo(String value) {
            addCriterion("LastCapADSL =", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslNotEqualTo(String value) {
            addCriterion("LastCapADSL <>", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslGreaterThan(String value) {
            addCriterion("LastCapADSL >", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslGreaterThanOrEqualTo(String value) {
            addCriterion("LastCapADSL >=", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslLessThan(String value) {
            addCriterion("LastCapADSL <", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslLessThanOrEqualTo(String value) {
            addCriterion("LastCapADSL <=", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslLike(String value) {
            addCriterion("LastCapADSL like", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslNotLike(String value) {
            addCriterion("LastCapADSL not like", value, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslIn(List<String> values) {
            addCriterion("LastCapADSL in", values, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslNotIn(List<String> values) {
            addCriterion("LastCapADSL not in", values, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslBetween(String value1, String value2) {
            addCriterion("LastCapADSL between", value1, value2, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapadslNotBetween(String value1, String value2) {
            addCriterion("LastCapADSL not between", value1, value2, "lastcapadsl");
            return (Criteria) this;
        }

        public Criteria andLastcapmacIsNull() {
            addCriterion("LastCapMac is null");
            return (Criteria) this;
        }

        public Criteria andLastcapmacIsNotNull() {
            addCriterion("LastCapMac is not null");
            return (Criteria) this;
        }

        public Criteria andLastcapmacEqualTo(String value) {
            addCriterion("LastCapMac =", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacNotEqualTo(String value) {
            addCriterion("LastCapMac <>", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacGreaterThan(String value) {
            addCriterion("LastCapMac >", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacGreaterThanOrEqualTo(String value) {
            addCriterion("LastCapMac >=", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacLessThan(String value) {
            addCriterion("LastCapMac <", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacLessThanOrEqualTo(String value) {
            addCriterion("LastCapMac <=", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacLike(String value) {
            addCriterion("LastCapMac like", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacNotLike(String value) {
            addCriterion("LastCapMac not like", value, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacIn(List<String> values) {
            addCriterion("LastCapMac in", values, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacNotIn(List<String> values) {
            addCriterion("LastCapMac not in", values, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacBetween(String value1, String value2) {
            addCriterion("LastCapMac between", value1, value2, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapmacNotBetween(String value1, String value2) {
            addCriterion("LastCapMac not between", value1, value2, "lastcapmac");
            return (Criteria) this;
        }

        public Criteria andLastcapipIsNull() {
            addCriterion("LastCapIP is null");
            return (Criteria) this;
        }

        public Criteria andLastcapipIsNotNull() {
            addCriterion("LastCapIP is not null");
            return (Criteria) this;
        }

        public Criteria andLastcapipEqualTo(String value) {
            addCriterion("LastCapIP =", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipNotEqualTo(String value) {
            addCriterion("LastCapIP <>", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipGreaterThan(String value) {
            addCriterion("LastCapIP >", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipGreaterThanOrEqualTo(String value) {
            addCriterion("LastCapIP >=", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipLessThan(String value) {
            addCriterion("LastCapIP <", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipLessThanOrEqualTo(String value) {
            addCriterion("LastCapIP <=", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipLike(String value) {
            addCriterion("LastCapIP like", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipNotLike(String value) {
            addCriterion("LastCapIP not like", value, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipIn(List<String> values) {
            addCriterion("LastCapIP in", values, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipNotIn(List<String> values) {
            addCriterion("LastCapIP not in", values, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipBetween(String value1, String value2) {
            addCriterion("LastCapIP between", value1, value2, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcapipNotBetween(String value1, String value2) {
            addCriterion("LastCapIP not between", value1, value2, "lastcapip");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeIsNull() {
            addCriterion("LastCapTime is null");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeIsNotNull() {
            addCriterion("LastCapTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeEqualTo(Integer value) {
            addCriterion("LastCapTime =", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeNotEqualTo(Integer value) {
            addCriterion("LastCapTime <>", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeGreaterThan(Integer value) {
            addCriterion("LastCapTime >", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("LastCapTime >=", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeLessThan(Integer value) {
            addCriterion("LastCapTime <", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeLessThanOrEqualTo(Integer value) {
            addCriterion("LastCapTime <=", value, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeIn(List<Integer> values) {
            addCriterion("LastCapTime in", values, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeNotIn(List<Integer> values) {
            addCriterion("LastCapTime not in", values, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeBetween(Integer value1, Integer value2) {
            addCriterion("LastCapTime between", value1, value2, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andLastcaptimeNotBetween(Integer value1, Integer value2) {
            addCriterion("LastCapTime not between", value1, value2, "lastcaptime");
            return (Criteria) this;
        }

        public Criteria andCapipIsNull() {
            addCriterion("CapIP is null");
            return (Criteria) this;
        }

        public Criteria andCapipIsNotNull() {
            addCriterion("CapIP is not null");
            return (Criteria) this;
        }

        public Criteria andCapipEqualTo(Integer value) {
            addCriterion("CapIP =", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipNotEqualTo(Integer value) {
            addCriterion("CapIP <>", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipGreaterThan(Integer value) {
            addCriterion("CapIP >", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipGreaterThanOrEqualTo(Integer value) {
            addCriterion("CapIP >=", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipLessThan(Integer value) {
            addCriterion("CapIP <", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipLessThanOrEqualTo(Integer value) {
            addCriterion("CapIP <=", value, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipIn(List<Integer> values) {
            addCriterion("CapIP in", values, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipNotIn(List<Integer> values) {
            addCriterion("CapIP not in", values, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipBetween(Integer value1, Integer value2) {
            addCriterion("CapIP between", value1, value2, "capip");
            return (Criteria) this;
        }

        public Criteria andCapipNotBetween(Integer value1, Integer value2) {
            addCriterion("CapIP not between", value1, value2, "capip");
            return (Criteria) this;
        }

        public Criteria andVirtualidIsNull() {
            addCriterion("VirtualID is null");
            return (Criteria) this;
        }

        public Criteria andVirtualidIsNotNull() {
            addCriterion("VirtualID is not null");
            return (Criteria) this;
        }

        public Criteria andVirtualidEqualTo(Integer value) {
            addCriterion("VirtualID =", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidNotEqualTo(Integer value) {
            addCriterion("VirtualID <>", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidGreaterThan(Integer value) {
            addCriterion("VirtualID >", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidGreaterThanOrEqualTo(Integer value) {
            addCriterion("VirtualID >=", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidLessThan(Integer value) {
            addCriterion("VirtualID <", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidLessThanOrEqualTo(Integer value) {
            addCriterion("VirtualID <=", value, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidIn(List<Integer> values) {
            addCriterion("VirtualID in", values, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidNotIn(List<Integer> values) {
            addCriterion("VirtualID not in", values, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidBetween(Integer value1, Integer value2) {
            addCriterion("VirtualID between", value1, value2, "virtualid");
            return (Criteria) this;
        }

        public Criteria andVirtualidNotBetween(Integer value1, Integer value2) {
            addCriterion("VirtualID not between", value1, value2, "virtualid");
            return (Criteria) this;
        }

        public Criteria andLastcapportIsNull() {
            addCriterion("LastCapPort is null");
            return (Criteria) this;
        }

        public Criteria andLastcapportIsNotNull() {
            addCriterion("LastCapPort is not null");
            return (Criteria) this;
        }

        public Criteria andLastcapportEqualTo(Integer value) {
            addCriterion("LastCapPort =", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportNotEqualTo(Integer value) {
            addCriterion("LastCapPort <>", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportGreaterThan(Integer value) {
            addCriterion("LastCapPort >", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportGreaterThanOrEqualTo(Integer value) {
            addCriterion("LastCapPort >=", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportLessThan(Integer value) {
            addCriterion("LastCapPort <", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportLessThanOrEqualTo(Integer value) {
            addCriterion("LastCapPort <=", value, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportIn(List<Integer> values) {
            addCriterion("LastCapPort in", values, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportNotIn(List<Integer> values) {
            addCriterion("LastCapPort not in", values, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportBetween(Integer value1, Integer value2) {
            addCriterion("LastCapPort between", value1, value2, "lastcapport");
            return (Criteria) this;
        }

        public Criteria andLastcapportNotBetween(Integer value1, Integer value2) {
            addCriterion("LastCapPort not between", value1, value2, "lastcapport");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table account
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}