package com.skeye.yagout.dal.model;

public class Dailinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.AdslAccount
     *
     * @mbggenerated
     */
    private String adslaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.Passwd
     *
     * @mbggenerated
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.DailTime
     *
     * @mbggenerated
     */
    private Integer dailtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.DailIP
     *
     * @mbggenerated
     */
    private Integer dailip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.SessionID
     *
     * @mbggenerated
     */
    private Integer sessionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.DailType
     *
     * @mbggenerated
     */
    private Integer dailtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.DailMac
     *
     * @mbggenerated
     */
    private String dailmac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dailinfo.Handled
     *
     * @mbggenerated
     */
    private Integer handled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.ID
     *
     * @return the value of dailinfo.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.ID
     *
     * @param id the value for dailinfo.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.AdslAccount
     *
     * @return the value of dailinfo.AdslAccount
     *
     * @mbggenerated
     */
    public String getAdslaccount() {
        return adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.AdslAccount
     *
     * @param adslaccount the value for dailinfo.AdslAccount
     *
     * @mbggenerated
     */
    public void setAdslaccount(String adslaccount) {
        this.adslaccount = adslaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.Passwd
     *
     * @return the value of dailinfo.Passwd
     *
     * @mbggenerated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.Passwd
     *
     * @param passwd the value for dailinfo.Passwd
     *
     * @mbggenerated
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.DailTime
     *
     * @return the value of dailinfo.DailTime
     *
     * @mbggenerated
     */
    public Integer getDailtime() {
        return dailtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.DailTime
     *
     * @param dailtime the value for dailinfo.DailTime
     *
     * @mbggenerated
     */
    public void setDailtime(Integer dailtime) {
        this.dailtime = dailtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.DailIP
     *
     * @return the value of dailinfo.DailIP
     *
     * @mbggenerated
     */
    public Integer getDailip() {
        return dailip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.DailIP
     *
     * @param dailip the value for dailinfo.DailIP
     *
     * @mbggenerated
     */
    public void setDailip(Integer dailip) {
        this.dailip = dailip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.SessionID
     *
     * @return the value of dailinfo.SessionID
     *
     * @mbggenerated
     */
    public Integer getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.SessionID
     *
     * @param sessionid the value for dailinfo.SessionID
     *
     * @mbggenerated
     */
    public void setSessionid(Integer sessionid) {
        this.sessionid = sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.DailType
     *
     * @return the value of dailinfo.DailType
     *
     * @mbggenerated
     */
    public Integer getDailtype() {
        return dailtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.DailType
     *
     * @param dailtype the value for dailinfo.DailType
     *
     * @mbggenerated
     */
    public void setDailtype(Integer dailtype) {
        this.dailtype = dailtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.DailMac
     *
     * @return the value of dailinfo.DailMac
     *
     * @mbggenerated
     */
    public String getDailmac() {
        return dailmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.DailMac
     *
     * @param dailmac the value for dailinfo.DailMac
     *
     * @mbggenerated
     */
    public void setDailmac(String dailmac) {
        this.dailmac = dailmac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dailinfo.Handled
     *
     * @return the value of dailinfo.Handled
     *
     * @mbggenerated
     */
    public Integer getHandled() {
        return handled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dailinfo.Handled
     *
     * @param handled the value for dailinfo.Handled
     *
     * @mbggenerated
     */
    public void setHandled(Integer handled) {
        this.handled = handled;
    }
}