package com.skeye.yagout.dal.model;

public class Privilegeobj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilegeobj.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilegeobj.ObjName
     *
     * @mbggenerated
     */
    private String objname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilegeobj.ObjType
     *
     * @mbggenerated
     */
    private Integer objtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column privilegeobj.ObjIdentity
     *
     * @mbggenerated
     */
    private String objidentity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilegeobj.ID
     *
     * @return the value of privilegeobj.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilegeobj.ID
     *
     * @param id the value for privilegeobj.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilegeobj.ObjName
     *
     * @return the value of privilegeobj.ObjName
     *
     * @mbggenerated
     */
    public String getObjname() {
        return objname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilegeobj.ObjName
     *
     * @param objname the value for privilegeobj.ObjName
     *
     * @mbggenerated
     */
    public void setObjname(String objname) {
        this.objname = objname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilegeobj.ObjType
     *
     * @return the value of privilegeobj.ObjType
     *
     * @mbggenerated
     */
    public Integer getObjtype() {
        return objtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilegeobj.ObjType
     *
     * @param objtype the value for privilegeobj.ObjType
     *
     * @mbggenerated
     */
    public void setObjtype(Integer objtype) {
        this.objtype = objtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column privilegeobj.ObjIdentity
     *
     * @return the value of privilegeobj.ObjIdentity
     *
     * @mbggenerated
     */
    public String getObjidentity() {
        return objidentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column privilegeobj.ObjIdentity
     *
     * @param objidentity the value for privilegeobj.ObjIdentity
     *
     * @mbggenerated
     */
    public void setObjidentity(String objidentity) {
        this.objidentity = objidentity;
    }
}