package com.skeye.yagout.dal.model;

public class Systemadmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemadmin.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemadmin.UserName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column systemadmin.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemadmin.ID
     *
     * @return the value of systemadmin.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemadmin.ID
     *
     * @param id the value for systemadmin.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemadmin.UserName
     *
     * @return the value of systemadmin.UserName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemadmin.UserName
     *
     * @param username the value for systemadmin.UserName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column systemadmin.Password
     *
     * @return the value of systemadmin.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column systemadmin.Password
     *
     * @param password the value for systemadmin.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}