package com.skeye.yagout.dal.model;

public class YagoutRolePermissionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yagout_role_permissions.permissions_no
     *
     * @mbggenerated
     */
    private Integer permissionsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yagout_role_permissions.role_no
     *
     * @mbggenerated
     */
    private Integer roleNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_role_permissions.permissions_no
     *
     * @return the value of yagout_role_permissions.permissions_no
     *
     * @mbggenerated
     */
    public Integer getPermissionsNo() {
        return permissionsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_role_permissions.permissions_no
     *
     * @param permissionsNo the value for yagout_role_permissions.permissions_no
     *
     * @mbggenerated
     */
    public void setPermissionsNo(Integer permissionsNo) {
        this.permissionsNo = permissionsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yagout_role_permissions.role_no
     *
     * @return the value of yagout_role_permissions.role_no
     *
     * @mbggenerated
     */
    public Integer getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yagout_role_permissions.role_no
     *
     * @param roleNo the value for yagout_role_permissions.role_no
     *
     * @mbggenerated
     */
    public void setRoleNo(Integer roleNo) {
        this.roleNo = roleNo;
    }
}