package com.yagout.defense.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.yagout.defense.dal.model.ApVisitor;
import com.yagout.defense.dal.model.ApVisitorExample;

public interface ApVisitorMapper {
	int batchUpdate(Map<String,List<ApVisitor>> apVisitorList);
	
	int batchInsert(Map<String,List<ApVisitor>> apVisitorList);
	
	int deleteApVisitors(List<String> macs);
	
    List<Map<String,Object>> selectAll(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int countByExample(ApVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int deleteByExample(ApVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int insert(ApVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int insertSelective(ApVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    List<ApVisitor> selectByExample(ApVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    ApVisitor selectByPrimaryKey(String mac);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ApVisitor record, @Param("example") ApVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ApVisitor record, @Param("example") ApVisitorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ApVisitor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ap_visitor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ApVisitor record);
}