package com.yagout.defense.biz.bean;

public class StationAdHocBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.mac
     *
     * @mbggenerated
     */
    private String mac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.maker
     *
     * @mbggenerated
     */
    private String maker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.reserved1
     *
     * @mbggenerated
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ad_hoc.reserved2
     *
     * @mbggenerated
     */
    private Integer reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.mac
     *
     * @return the value of station_ad_hoc.mac
     *
     * @mbggenerated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.mac
     *
     * @param mac the value for station_ad_hoc.mac
     *
     * @mbggenerated
     */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.maker
     *
     * @return the value of station_ad_hoc.maker
     *
     * @mbggenerated
     */
    public String getMaker() {
        return maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.maker
     *
     * @param maker the value for station_ad_hoc.maker
     *
     * @mbggenerated
     */
    public void setMaker(String maker) {
        this.maker = maker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.name
     *
     * @return the value of station_ad_hoc.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.name
     *
     * @param name the value for station_ad_hoc.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.remarks
     *
     * @return the value of station_ad_hoc.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.remarks
     *
     * @param remarks the value for station_ad_hoc.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.reserved1
     *
     * @return the value of station_ad_hoc.reserved1
     *
     * @mbggenerated
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.reserved1
     *
     * @param reserved1 the value for station_ad_hoc.reserved1
     *
     * @mbggenerated
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ad_hoc.reserved2
     *
     * @return the value of station_ad_hoc.reserved2
     *
     * @mbggenerated
     */
    public Integer getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ad_hoc.reserved2
     *
     * @param reserved2 the value for station_ad_hoc.reserved2
     *
     * @mbggenerated
     */
    public void setReserved2(Integer reserved2) {
        this.reserved2 = reserved2;
    }
}